### ISSUE TITLE
win32 wheel build is broken

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-healpix#319]
Probably caused by #316 cc @lpsinger 

Example log: https://github.com/astropy/astropy-healpix/actions/runs/28384215558/job/84094560015

```
Creating library build\...\astropy_healpix\_core.lib and object build\...\astropy_healpix\_core.exp
  _core.obj : error LNK2001: unresolved external symbol __BitScanReverse64
  build\lib.win32-cpython-310\astropy_healpix\_core.pyd : fatal error LNK1120: 1 unresolved externals
  error: command 'C:\\...\\x86\\link.exe' failed with exit code 1120
```
