### ISSUE TITLE
astropy-healpix 2.0.0:  Build fails on Guix

### ISSUE THREAD

**Issue by Hellseher** [astropy/astropy-healpix#322]
Hi,

During monthly update for Astro* related software in Gux I've noticed that astorpy-healpix started failing to build on v2.0.0
```
running build_ext
building 'astropy_healpix._core' extension
creating build/temp.linux-x86_64-cpython-312/astropy_healpix
creating build/temp.linux-x86_64-cpython-312/cextern/astrometry.net
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fPIC -DNPY_TARGET_VERSION=NPY_2_0_API_VERSION -DNPY_NO_DEPRECATED_API=NPY_2_0_API_VERSION -DPy_LIMITED_API=0x030A0000 -I/gnu/store/p48ak2vih0s11adlxwr53b3vs60m46lq-python-numpy-2.3.1/lib/python3.12/site-packages/numpy/_core/include -Icextern/astrometry.net -Iastropy_healpix -Icextern/numpy -I/gnu/store/rh3vyrap1hswvgn122i7n7p5yba2spid-python-3.12.12/include/python3.12 -c astropy_healpix/_core.c -o build/temp.linux-x86_64-cpython-312/astropy_healpix/_core.o -O2
In file included from astropy_healpix/_core.c:10:
astropy_healpix/_core.c: In function ‘bit_scan_reverse_loop’:
astropy_healpix/_core.c:313:25: error: argument 1 in call to function ‘__builtin_stdc_leading_zeros’ has signed type
  313 |             *out = 63 - stdc_leading_zeros(in);
      |                         ^~~~~~~~~~~~~~~~~~
error: command '/gnu/store/bl3qw29h2582k7hpifm90g508z838swc-gcc-14.3.0/bin/gcc' failed with exit code 1
error: in phase 'build': uncaught exception:
%exception #<&invoke-error program: "python" arguments: ("-c" "import sys, importlib, json\nbackend_path = json.loads(sys.argv[1]) or []\nbackend_path.extend(sys.path)\nsys.path = backend_path\nconfig_settings = json.loads(sys.argv[4])\nbuilder = importlib.import_module(sys.argv[2])\nbuilder.build_wheel(sys.argv[3], config_settings=config_settings)" "[]" "setuptools.build_meta" "dist" "{}") exit-status: 1 term-signal: #f stop-signal: #f>
```
v1.1.3 has been built successfully entire year without any issues.

It looks like it comes from this part:
``` c
static void bit_scan_reverse_loop(
    char **args, const npy_intp *dimensions, const npy_intp *steps, void *data)
{
    npy_intp i, n = dimensions[0];

    for (i = 0; i < n; i ++)
    {
        int64_t  in = *(int64_t *) &args[0][i * steps[0]];
        int    *out =  (int *)     &args[1][i * steps[1]];
        #if __has_include(<stdbit.h>)
            *out = 63 - stdc_leading_zeros(in);
        #elif defined(_MSC_VER)
            unsigned long index;
            if (_BitScanReverse64(&index, in))
                *out = index;
            else
                *out = -1;
        #else
            *out = 63 - __builtin_clzll(in);
        #endif
    }
}

```

Inputs:
Python 3.12.12

- python-extension-helpers@1.4.0
- python-pytest@9.0.2
- python-setuptools@80.9.0
- python-setuptools-scm@8.3.1
- python-astropy@8.0.1
- python-numpy@2.3.1

**Comment by lpsinger** [comment]
Does it build properly if you set the environment variable CFLAGS="-std=gnu23"?

**Comment by Hellseher** [comment]
Hi,

It fails with the same error, unfortunately.

**Comment by lpsinger** [comment]
How about version 2.0.1?

**Comment by Hellseher** [comment]
It works like a charm!
Thanks for addressing the issue.

I'll include 2.0.1 in the next month Guix Astro update cycle.

Reproducer:
```
guix time-machine --commit=a6a2d1bf9ff94e86a96789ef413ccf3ecf16f11e -- build --with-version=python-astropy-healpix=2.0.1 python-astropy-healpix --log-file
```

Full build log:
[vijn2xj31jy1kdw204hl1v1nlwncyc-python-astropy-healpix-2.0.1.drv.gz](https://github.com/user-attachments/files/30283798/vijn2xj31jy1kdw204hl1v1nlwncyc-python-astropy-healpix-2.0.1.drv.gz)
